# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1dbe0f15d4cd84464e4fc84cc4d62de0f76dfcc5d2f20bcd0aad11a3238acd4bc25298dad9aa4e5d1f6508650d2e06509851396b8941a98801827f1387e15000

test:
  secret_key_base: aaca59c418ae17c9d52001fd00842cbb74e043bf27d31081efbdf586dbb86cdaf36654ef24c65c78faf20626feda8f947c5d66f1579c2a56ea1b90fb0fa11445

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
